### ISSUE TITLE
Request to bundle fzy-lua

### ISSUE THREAD

**Issue by archie-judd** [swarn/fzy-lua#15]
Hi @swarn 

I've developed  a Neovim plugin ([telescope-words](https://github.com/archie-judd/telescope-words.nvim)) for searching dictionary and thesaurus entries, and I'd like to bundle `fzy-lua` with it to improve its functionality. I want to check you are okay with this before I do so.

Thank you for your work on `fzy`, it's a great library!

Best regards

**Comment by swarn** [comment]
Looks great, go for it!
